## filter

In [1]:
import cv2 as cv
import numpy as np
import scipy.signal as sig

# A1 = 3x3 matrix
A1 = np.array([[1,3, 1],
                    [0, -1, 1],
                    [2, 2, -1]])

# Template
kernel = np.array([[1,2],
                [0,-1]])

# kernel = np.array ([[8, 9, 10, 11, 12],
#                     [15, 16, 17, 18, 19],
#                     [22, 23, 24, 25, 26],
#                     [29, 30, 31, 32, 33]])

#dap an ơ tam 
#cross-correlation
print(sig.correlate2d(A1, kernel, boundary='fill', mode='same'))

#convolution
# print(sig.convolve(A1, kernel, mode='same'))

#median filter = lọc trung vị
# print(sig.medfilt(A1, kernel_size=None))

[[ 8  4  1]
 [-4  2  1]
 [ 6  0 -1]]


## image processing

In [2]:
import cv2
import numpy as np

# open cv tra ve gia tri cac kenh mau mac dinh la B G R
img = cv2.imread('images/thu.jpg')
# copy image
img_clone = img.copy()
# Lay kich thuoc cua anh, anh co 307200 pixels
# print(img_clone.size)
# print(type(img_clone))
# width= so cot, height= so hang, depth= so kenh mau
print(img_clone.shape)

# Lay ma tran theo tung kenh mau
B = img[:,:,0] 
G = img[:,:,1] 
R = img[:,:,2]

B = B*0.114
G = G*0.587
R = R*0.299
gray = B+G+R
imgGray = img.copy()
for i in range(3):
    imgGray[:,:,i] = gray

cv2.imshow('Image Gray', imgGray)
cv2.waitKey(0)
cv2.destroyAllWindows()

p1 = [50, 60]
p2 = [320, 320]
# toa do lan luot la 50,60 320,320
# Cut = imgGray[50:320, 60:320]
Cut = imgGray[p1[0]:p2[0], p1[1]:p2[1]]
cv2.imshow('Region of Interest', Cut)
cv2.waitKey(0)
cv2.destroyAllWindows()

(320, 320, 3)


In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
from numpy.core.fromnumeric import size

# open cv tra ve gia tri cac kenh mau mac dinh la B G R
img = cv2.imread('images/thu.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
im = img.copy()

cv2.imshow('image',im)

# histr = cv2.calcHist([im],[0],None,[256],[0,256])
# plt.plot(histr)
# plt.show()
# plt.close()

# ret, th1 = cv2.threshold(im, 80, 120, cv2.THRESH_BINARY)
th2 = cv2.adaptiveThreshold(im, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY,11,2)

# cv2.imshow('th1',th1)
cv2.imshow('th',th2)

kernel = np.ones((3,3))
binImg = th2/255
sizeSrc = th2.shape
sizeKernel = kernel.shape
# Them padding
R = sizeSrc[0] + sizeKernel[0] - 1
C = sizeSrc[1] + sizeKernel[1] - 1

N = np.zeros((R, C))
for i in range(sizeSrc[0]):
    for j in range(sizeSrc[1]):
        N[i+1, j+1] = binImg[i, j]
# # Dilation
for i in range(sizeSrc[0]):
    for j in range(sizeSrc[1]):
        k = N[i:i+sizeKernel[0], j:j+sizeKernel[1]]
        result = (k == kernel)
        final = np.all(result == True)
        if final: 
            binImg[i,j] = 1
        else:
            binImg[i,j] = 0

# Erosion
# for i in range(sizeSrc[0]):
#     for j in range(sizeSrc[1]):
#         k = N[i:i+sizeKernel[0], j:j+sizeKernel[1]]
#         result = (k == kernel)
#         final = np.any(result == True)
#         if final: 
#             binImg[i,j] = 1
#         else:
#             binImg[i,j] = 0

cv2.imshow('Morphological', binImg)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [2]:
import cv2 as cv
import numpy as np
import scipy.ndimage as nd

# A1 = 8x6 matrix
A1 = np.array([[0,0,0,0,0,0,0,0],
               [0,0,0,1,1,0,0,0],
               [0,1,1,1,1,1,1,0],
               [0,0,1,1,1,0,1,0],
               [0,1,1,1,1,1,1,0],
               [0,0,0,0,0,0,0,0]])

# A1 = np.array ([[0, 0, 0],
#                 [0, 1, 1],
#                 [1, 1, 1]])

# Cross-shaped kernel (structuring element)
kernel = np.array ([[0, 1, 0],
                 [1, 1, 1],
                 [0, 1, 1]])



# # Dilation
# print(nd.binary_dilation(A1, structure=kernel).astype(A1.dtype))


# Erosion
# print(nd.binary_erosion(A1, structure=kernel).astype(A1.dtype))

# Opening
# print(nd.binary_opening(A1,structure=kernel).astype(A1.dtype))

# Closing
print(nd.binary_closing(A1, structure=kernel).astype(A1.dtype))


[[0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]
